# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ship.v1 import ship_pb2 as ship_dot_v1_dot_ship__pb2


class ShipServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetShips = channel.unary_unary(
                '/ship.v1.ShipService/GetShips',
                request_serializer=ship_dot_v1_dot_ship__pb2.Empty.SerializeToString,
                response_deserializer=ship_dot_v1_dot_ship__pb2.Ships.FromString,
                )
        self.GetShip = channel.unary_unary(
                '/ship.v1.ShipService/GetShip',
                request_serializer=ship_dot_v1_dot_ship__pb2.GetShipRequest.SerializeToString,
                response_deserializer=ship_dot_v1_dot_ship__pb2.Ship.FromString,
                )
        self.MoveTo = channel.unary_unary(
                '/ship.v1.ShipService/MoveTo',
                request_serializer=ship_dot_v1_dot_ship__pb2.MoveToRequest.SerializeToString,
                response_deserializer=ship_dot_v1_dot_ship__pb2.Empty.FromString,
                )
        self.SensorPing = channel.unary_unary(
                '/ship.v1.ShipService/SensorPing',
                request_serializer=ship_dot_v1_dot_ship__pb2.SensorPingRequest.SerializeToString,
                response_deserializer=ship_dot_v1_dot_ship__pb2.PingSummary.FromString,
                )


class ShipServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetShips(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetShip(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveTo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SensorPing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShipServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetShips': grpc.unary_unary_rpc_method_handler(
                    servicer.GetShips,
                    request_deserializer=ship_dot_v1_dot_ship__pb2.Empty.FromString,
                    response_serializer=ship_dot_v1_dot_ship__pb2.Ships.SerializeToString,
            ),
            'GetShip': grpc.unary_unary_rpc_method_handler(
                    servicer.GetShip,
                    request_deserializer=ship_dot_v1_dot_ship__pb2.GetShipRequest.FromString,
                    response_serializer=ship_dot_v1_dot_ship__pb2.Ship.SerializeToString,
            ),
            'MoveTo': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveTo,
                    request_deserializer=ship_dot_v1_dot_ship__pb2.MoveToRequest.FromString,
                    response_serializer=ship_dot_v1_dot_ship__pb2.Empty.SerializeToString,
            ),
            'SensorPing': grpc.unary_unary_rpc_method_handler(
                    servicer.SensorPing,
                    request_deserializer=ship_dot_v1_dot_ship__pb2.SensorPingRequest.FromString,
                    response_serializer=ship_dot_v1_dot_ship__pb2.PingSummary.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ship.v1.ShipService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ShipService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetShips(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ship.v1.ShipService/GetShips',
            ship_dot_v1_dot_ship__pb2.Empty.SerializeToString,
            ship_dot_v1_dot_ship__pb2.Ships.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetShip(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ship.v1.ShipService/GetShip',
            ship_dot_v1_dot_ship__pb2.GetShipRequest.SerializeToString,
            ship_dot_v1_dot_ship__pb2.Ship.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MoveTo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ship.v1.ShipService/MoveTo',
            ship_dot_v1_dot_ship__pb2.MoveToRequest.SerializeToString,
            ship_dot_v1_dot_ship__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SensorPing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ship.v1.ShipService/SensorPing',
            ship_dot_v1_dot_ship__pb2.SensorPingRequest.SerializeToString,
            ship_dot_v1_dot_ship__pb2.PingSummary.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
