# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: util/v1/util.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12util/v1/util.proto\x12\x07util.v1\")\n\x06Vector\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x42\x38Z6github.com/austinphilp/space-server/proto/util/v1;utilb\x06proto3')



_VECTOR = DESCRIPTOR.message_types_by_name['Vector']
Vector = _reflection.GeneratedProtocolMessageType('Vector', (_message.Message,), {
  'DESCRIPTOR' : _VECTOR,
  '__module__' : 'util.v1.util_pb2'
  # @@protoc_insertion_point(class_scope:util.v1.Vector)
  })
_sym_db.RegisterMessage(Vector)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z6github.com/austinphilp/space-server/proto/util/v1;util'
  _VECTOR._serialized_start=31
  _VECTOR._serialized_end=72
# @@protoc_insertion_point(module_scope)
